project:
  type: website

website:
  title: "ISSS608"
  navbar:
    left:
      - text: "Hands-on Exercises"
        menu:
          - text: "Hands-on Exercise 1" 
            href: "Hands-on_ex/Hands-on_Ex01/Hands-on_Ex01.html"
        
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true

editor: visual
