project:
  type: website

website:
  title: "ISSS608"
  navbar:
    left:
      - text: "Hands-on Exercises"
        menu:
          - text: "Hands-on Exercise 1" 
            href: "Hands-on_ex/Hands-on_Ex01/Hands-on_Ex01.html"
            
          - text: "Hands-on Exercise 2" 
            href: "Hands-on_ex/Hands-on_Ex02/Hands-on_Ex02.html"
            
          - text: "Hands-on Exercise 3" 
            href: "Hands-on_ex/Hands-on_Ex03/Hands-on_Ex03.html"
            
          - text: "Hands-on Exercise 3b" 
            href: "Hands-on_ex/Hands-on_Ex03b/Hands-on_Ex03b.html"
            
          - text: "Hands-on Exercise 4a" 
            href: "Hands-on_ex/Hands-on_Ex04a/Hands-on_Ex04a.html"
          
          - text: "Hands-on Exercise_4b" 
            href: "Hands-on_ex/Hands-on_Ex04b/Hands-on_Ex04b.html"
            
          - text: "Hands-on Exercise 4c" 
            href: "Hands-on_ex/Hands-on_Ex04c/Hands-on_Ex04c.html"
            
          - text: "Hands-on Exercise 4d" 
            href: "Hands-on_ex/Hands-on_Ex04d/Hands-on_Ex04d.html"
            
          
            
      - text: "In-Class Exercises"
        menu:
          - text: "In-Class Exercise 1" 
            href: "In-Class_ex/In-Class_Ex01/In-Class_Ex01.html"
            
          - text: "In-Class Exercise 4" 
            href: "In-Class_ex/In-Class_Ex04/In-Class_Ex04.html"
            
      - text: "Take-Home Exercises"
        menu:
          - text: "Take-Home Exercise 1" 
            href: "Take-Home_Ex/Take-Home_Ex01/Take-Home_Ex01.html"
        
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: spacelab
    css: styles.css
    toc: true
    execute:
      warning: false

editor: visual
