---
title: "In-Class_Ex05"
---

## Importing library

```{r}
#| warning: false
pacman::p_load(tidyverse, readxl, SmartEDA, easystats, gtsummary)
```

## Data import

```{r}
car_resale <- read_xls("data/ToyotaCorolla.xls","data")
```

```{r}
list(car_resale)
```

```{r}
glimpse(car_resale)
```

```{r}
summary(car_resale)
```

## Data Overview

```{r}
car_resale %>%
  ExpData(type = 1)
```

```{r}
car_resale %>%
  ExpData(type = 2)
```

```{r}
cols <- c("Mfg_Month", "HP_Bin", "CC_bin", "Doors", "Gears", "Cylinders", "Fuel_Type", "Color", "ABS", "Airbag_1",
          "Met_Color", "Automatic", "Mfr_Guarantee", "BOVAG_Guarantee", "CD_Player", "Airbag_2", "Airco", "Automatic_airco", 
          "Boardcomputer", "Mistlamps", "Central_Lock", "Powered_Windows", "Power_Steering", "Radio",
          "Sport_Model", "Backseat_Divider", "Metallic_Rim", "Radio_cassette", "Tow_Bar")

```

```{r}
library(readxl)
library(dplyr)

car_resale <- read_xls("data/ToyotaCorolla.xls",
                       sheet = "data") %>%
  mutate(Id = as.character(Id)) %>%
  mutate(across(all_of(cols), as.factor))

  
```

```{r}
car_resale
```

```{r}
car_resale %>%
  ExpNumViz(target = NULL,
            nlim = 10,
            Page = c(2,2))
```

```{r}
car_resale %>%
  ExpNumViz(target="Price",
            nlim=10,
            Page=c(2,2))
```

```{r fig-width=12, fig-height=10}

car_resale %>%
  ExpCatViz(target=NULL,
            col = "sky blue",
            clim=10,
            margin=2,
            Page=c(4,4),
            sample=16)
```

```{r}
model <- lm(Price ~ Age_08_04 + Mfg_Year + KM + Weight + Guarantee_Period, data = car_resale)
model
```

```{r}
check_collinearity(model)
```

```{r}
check_c <- check_collinearity(model)
plot(check_c)
```

```{r}
model1 <- lm(Price ~ Age_08_04 + Mfg_Year + KM + Weight + Guarantee_Period, data = car_resale)
model1
```

```{r}
check_normality(model1)
```

```{r}
plot(check_heteroscedasticity(model1) )
```

```{r}
model1 <- lm(Price ~ Age_08_04 + KM + Weight + Guarantee_Period, data = car_resale)

plot (check_normality(model1))

```

```{r}
tbl_regression(model1,
               intercept = TRUE)
```

```{r}
summary(model1)
```

```{r}
p_model1 <- parameters(model1)
```

```{r}
plot(parameters(model1))
```

```{r}
library(ggstatsplot)
ggcoefstats(model1,
            output = "plot")
```
