---
title: "In-Class_Ex04"
---

## Getting Started

### Installing and loading r packages

```{r}
#| warning: false
pacman::p_load(haven,SmartEDA,tidyverse,tidymodels,ggdist,ggplot2)
```

```{r}
exam <- read_csv("data/Exam_data.csv",show_col_types = FALSE)
```

```{r}
ggplot(data = exam,
       aes(x = ENGLISH,
           y = CLASS)) +
  geom_boxplot()
```

```{r}
ggplot(exam, 
       aes(x = RACE, 
           y = ENGLISH)) +
  stat_halfeye(adjust = 0.5,
               justification = -0.2,
               .width = 0,
               point_colour = NA) +
  geom_boxplot(width = .20,
               outlier.shape = NA) +
  stat_dots(side = "left", 
            justification = 1.2, 
            binwidth = .5,
            dotsize = 2)
```
each dots represent each students
break down of my convenial box plot

dark = probility density
shows high level distribution trends to smooth out

dots plot provides a detail



"bayes" statistics not using 1 cup of point but using a range.


```{r}
churn_telecrom <-
  read_sas("data/churn_telecom.sas7bdat")%>%
    mutate(CHURN_FLG = factor(
      CHURN_FLG,
      levels = c("1","0"),
      labels = c("Churn","Non-Churn")
    ))
```


